toolbar: undo redo | forecolor | bold italic | alignleft aligncenter alignright | fontselect | code | link | image | quickimage | table |
plugins:
  - link
  - image
  - textcolor
  - code
  - table
  - quickbars
